create table Admin(Admin_ID char(2) NOT NULL PRIMARY KEY, Admin_Password varchar(15) NOT NULL);
create table Client_Address(Postal_Code char(6) NOT NULL PRIMARY KEY CHECK(LENGTH(Postal_Code)=6) CONSTRAINT valid_postal_code CHECK (Postal_Code ~ '^[0-9]{6}$'), City varchar(20) NOT NULL, State varchar(20) NOT NULL);
create table Client(Client_ID varchar(3) NOT NULL PRIMARY KEY, Name varchar(30) NOT NULL, Contact_No varchar(15) NOT NULL UNIQUE CHECK(LENGTH(Contact_No)=10) CONSTRAINT valid_contact_no CHECK (Contact_No ~ '^[0-9]{10}$'), DOB date NOT NULL, Aadhar_No varchar(12) DEFAULT NULL, Postal_Code char(6) NOT NULL, FOREIGN KEY (Postal_Code) REFERENCES Client_Address(Postal_Code));
create table Property(Property_ID varchar(6) NOT NULL PRIMARY KEY, Property_Type varchar(10) NOT NULL, Owner_ID varchar(3) NOT NULL, Date_Posted date NOT NULL, Property_Status varchar(10) NOT NULL, FOREIGN KEY (Owner_ID) REFERENCES Client(Client_ID));
create table Land(Plot_ID varchar(6) NOT NULL PRIMARY KEY, Plot_No varchar(5) NOT NULL, Street_No varchar(10) NOT NULL, Locality_Name varchar(20) NOT NULL, City varchar(20) NOT NULL, State varchar(20) NOT NULL, Pin_Code varchar(6) NOT NULL, Length int NOT NULL, Breadth int NOT NULL, Facing varchar(6) NOT NULL, Total_Cost bigint NOT NULL);
create table House(House_ID varchar(6) NOT NULL PRIMARY KEY, House_No varchar(5) NOT NULL, Street_No varchar(10) NOT NULL, Locality_Name varchar(20) NOT NULL, City varchar(20) NOT NULL, State varchar(20) NOT NULL, Pin_Code varchar(6) NOT NULL, Facing varchar(6) NOT NULL, BHK int, Parking bit NOT NULL DEFAULT '0', Total_Cost bigint NOT NULL);
create table Rent(Rent_ID varchar(6) NOT NULL PRIMARY KEY, Building_No varchar(5) NOT NULL, Street_No varchar(10) NOT NULL, Locality_Name varchar(20) NOT NULL, City varchar(20) NOT NULL, State varchar(20) NOT NULL, Pin_Code varchar(6) NOT NULL, Facing varchar(6) NOT NULL, BHK int, Parking bit NOT NULL DEFAULT '0', Tenant_Type varchar(20), Monthly_Rent bigint NOT NULL, Advance_Amount bigint NOT NULL);
create table Book(Book_ID varchar(5) NOT NULL PRIMARY KEY, Date_Booked date NOT NULL, Property_ID varchar(6) NOT NULL, Owner_ID varchar(3) NOT NULL, Buyer_ID varchar(3) NOT NULL, FOREIGN KEY (Property_ID) REFERENCES Property(Property_ID), FOREIGN KEY (Owner_ID) REFERENCES Client(Client_ID), FOREIGN KEY (Buyer_ID) REFERENCES Client(Client_ID));
create table Payment(Payment_ID varchar(7) NOT NULL PRIMARY KEY, Transaction_Ref_No varchar(10) NOT NULL UNIQUE, Payment_Status varchar(15) NOT NULL, Book_ID varchar(5) NOT NULL, Client_ID varchar(3) NOT NULL, FOREIGN KEY (Book_ID) REFERENCES Book(Book_ID) ON UPDATE CASCADE, FOREIGN KEY (Client_ID) REFERENCES Client(Client_ID));

